services:
  pg:
    image: postgres 
    environment:
      - POSTGRES_PASSWORD=admin
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  mysite:
    build: .
    ports:
      - '8081:8081'
    depends_on:
      pg:
        condition: service_healthy

